from vmtools._commands.binary_operations import Add
from vmtools._commands.binary_operations import Subtract
from vmtools._commands.binary_operations import And
from vmtools._commands.binary_operations import Or
from vmtools._commands.binary_operations import Equals
from vmtools._commands.binary_operations import GreaterThan
from vmtools._commands.binary_operations import LessThan
from vmtools._commands.unary_operations import Negate
from vmtools._commands.unary_operations import Not
from vmtools._commands.pushpop import Push
from vmtools._commands.pushpop import Pop
from vmtools._commands.branching import Label
from vmtools._commands.branching import GoTo
from vmtools._commands.branching import IfGoTo
from vmtools._commands.function import Call
from vmtools._commands.function import Function
from vmtools._commands.function import Return
